{
  "restrictedMaterials": [
    "DIAMOND_AXE",
    "DIAMOND_BOOTS",
    "DIAMOND_CHESTPLATE",
    "DIAMOND_HELMET",
    "DIAMOND_HOE",
    "DIAMOND_LEGGINGS",
    "DIAMOND_PICKAXE",
    "DIAMOND_SHOVEL",
    "DIAMOND_SWORD",

    "IRON_AXE",
    "IRON_BOOTS",
    "IRON_CHESTPLATE",
    "IRON_HELMET",
    "IRON_HOE",
    "IRON_LEGGINGS",
    "IRON_PICKAXE",
    "IRON_SHOVEL",
    "IRON_SWORD"
  ],
  "villagerRestricted": [
    "DIAMOND_AXE",
    "DIAMOND_BOOTS",
    "DIAMOND_CHESTPLATE",
    "DIAMOND_HELMET",
    "DIAMOND_HOE",
    "DIAMOND_LEGGINGS",
    "DIAMOND_PICKAXE",
    "DIAMOND_SHOVEL",
    "DIAMOND_SWORD"
  ]
}